/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package libspatdif;

public final class EExtension {
  public final static EExtension SD_CORE = new EExtension("SD_CORE");
  public final static EExtension SD_MEDIA = new EExtension("SD_MEDIA");
  public final static EExtension SD_INTERPOLATION = new EExtension("SD_INTERPOLATION");
  public final static EExtension SD_SOURCE_WIDTH = new EExtension("SD_SOURCE_WIDTH");
  public final static EExtension SD_DIRECT_TO_ONE = new EExtension("SD_DIRECT_TO_ONE");
  public final static EExtension SD_EXTENSION_ERROR = new EExtension("SD_EXTENSION_ERROR");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static EExtension swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + EExtension.class + " with value " + swigValue);
  }

  private EExtension(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private EExtension(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private EExtension(String swigName, EExtension swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static EExtension[] swigValues = { SD_CORE, SD_MEDIA, SD_INTERPOLATION, SD_SOURCE_WIDTH, SD_DIRECT_TO_ONE, SD_EXTENSION_ERROR };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

