/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package libspatdif;

public class sdEntityExtension extends sdEntity {
  private transient long swigCPtr;

  protected sdEntityExtension(long cPtr, boolean cMemoryOwn) {
    super(spatdiflib_wrapperJNI.sdEntityExtension_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(sdEntityExtension obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        spatdiflib_wrapperJNI.delete_sdEntityExtension(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public static SWIGTYPE_p_std__vectorT_EDescriptor_t getDescriptors() {
    return new SWIGTYPE_p_std__vectorT_EDescriptor_t(spatdiflib_wrapperJNI.sdEntityExtension_getDescriptors(), true);
  }

  public EExtension getExtensionName() {
    return EExtension.swigToEnum(spatdiflib_wrapperJNI.sdEntityExtension_getExtensionName(swigCPtr, this));
  }

  public SWIGTYPE_p_std__string getExtensionNameAsString() {
    return new SWIGTYPE_p_std__string(spatdiflib_wrapperJNI.sdEntityExtension_getExtensionNameAsString(swigCPtr, this), true);
  }

}
