/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package libspatdif;

public class sdEntity extends sdInterpolation {
  private transient long swigCPtr;

  protected sdEntity(long cPtr, boolean cMemoryOwn) {
    super(spatdiflib_wrapperJNI.sdEntity_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(sdEntity obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        spatdiflib_wrapperJNI.delete_sdEntity(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public int getNumberOfEvents() {
    return spatdiflib_wrapperJNI.sdEntity_getNumberOfEvents(swigCPtr, this);
  }

  public sdEvent getEvent(double time, EDescriptor descriptor) {
    long cPtr = spatdiflib_wrapperJNI.sdEntity_getEvent(swigCPtr, this, time, descriptor.swigValue());
    return (cPtr == 0) ? null : new sdEvent(cPtr, false);
  }

  public SWIGTYPE_p_std__multisetT_sdEvent_p_sdEventCompare_t getEventSet() {
    return new SWIGTYPE_p_std__multisetT_sdEvent_p_sdEventCompare_t(spatdiflib_wrapperJNI.sdEntity_getEventSet__SWIG_0(swigCPtr, this), true);
  }

  public SWIGTYPE_p_std__multisetT_sdEvent_p_sdEventCompare_t getEventSet(double time) {
    return new SWIGTYPE_p_std__multisetT_sdEvent_p_sdEventCompare_t(spatdiflib_wrapperJNI.sdEntity_getEventSet__SWIG_1(swigCPtr, this, time), true);
  }

  public SWIGTYPE_p_std__multisetT_sdEvent_p_sdEventCompare_t getEventSet(double start, double end) {
    return new SWIGTYPE_p_std__multisetT_sdEvent_p_sdEventCompare_t(spatdiflib_wrapperJNI.sdEntity_getEventSet__SWIG_2(swigCPtr, this, start, end), true);
  }

  public SWIGTYPE_p_std__multisetT_sdEvent_p_sdEventCompare_t getEventSet(double start, double end, EDescriptor descriptor) {
    return new SWIGTYPE_p_std__multisetT_sdEvent_p_sdEventCompare_t(spatdiflib_wrapperJNI.sdEntity_getEventSet__SWIG_3(swigCPtr, this, start, end, descriptor.swigValue()), true);
  }

  public SWIGTYPE_p_std__multisetT_sdEvent_p_sdEventCompare_t getNextEventSet(double time) {
    return new SWIGTYPE_p_std__multisetT_sdEvent_p_sdEventCompare_t(spatdiflib_wrapperJNI.sdEntity_getNextEventSet(swigCPtr, this, time), true);
  }

  public sdEvent getNextEvent(double time, EDescriptor descriptor) {
    long cPtr = spatdiflib_wrapperJNI.sdEntity_getNextEvent(swigCPtr, this, time, descriptor.swigValue());
    return (cPtr == 0) ? null : new sdEvent(cPtr, false);
  }

  public double getNextEventTime(double time) {
    return spatdiflib_wrapperJNI.sdEntity_getNextEventTime(swigCPtr, this, time);
  }

  public sdEvent getPreviousEvent(double time, EDescriptor descriptor) {
    long cPtr = spatdiflib_wrapperJNI.sdEntity_getPreviousEvent(swigCPtr, this, time, descriptor.swigValue());
    return (cPtr == 0) ? null : new sdEvent(cPtr, false);
  }

  public SWIGTYPE_p_std__multisetT_sdEvent_p_sdEventCompare_t getPreviousEventSet(double time) {
    return new SWIGTYPE_p_std__multisetT_sdEvent_p_sdEventCompare_t(spatdiflib_wrapperJNI.sdEntity_getPreviousEventSet(swigCPtr, this, time), true);
  }

  public double getPreviousEventTime(double time) {
    return spatdiflib_wrapperJNI.sdEntity_getPreviousEventTime(swigCPtr, this, time);
  }

  public sdEvent getFirstEvent(EDescriptor descriptor) {
    long cPtr = spatdiflib_wrapperJNI.sdEntity_getFirstEvent(swigCPtr, this, descriptor.swigValue());
    return (cPtr == 0) ? null : new sdEvent(cPtr, false);
  }

  public SWIGTYPE_p_std__multisetT_sdEvent_p_sdEventCompare_t getFirstEventSet() {
    return new SWIGTYPE_p_std__multisetT_sdEvent_p_sdEventCompare_t(spatdiflib_wrapperJNI.sdEntity_getFirstEventSet(swigCPtr, this), true);
  }

  public double getFirstEventTime() {
    return spatdiflib_wrapperJNI.sdEntity_getFirstEventTime(swigCPtr, this);
  }

  public sdEvent getLastEvent(EDescriptor descriptor) {
    long cPtr = spatdiflib_wrapperJNI.sdEntity_getLastEvent(swigCPtr, this, descriptor.swigValue());
    return (cPtr == 0) ? null : new sdEvent(cPtr, false);
  }

  public SWIGTYPE_p_std__multisetT_sdEvent_p_sdEventCompare_t getLastEventSet() {
    return new SWIGTYPE_p_std__multisetT_sdEvent_p_sdEventCompare_t(spatdiflib_wrapperJNI.sdEntity_getLastEventSet(swigCPtr, this), true);
  }

  public double getLastEventTime() {
    return spatdiflib_wrapperJNI.sdEntity_getLastEventTime(swigCPtr, this);
  }

  public sdEvent addEvent(double time, EDescriptor descriptor, SWIGTYPE_p_void value) {
    long cPtr = spatdiflib_wrapperJNI.sdEntity_addEvent__SWIG_0(swigCPtr, this, time, descriptor.swigValue(), SWIGTYPE_p_void.getCPtr(value));
    return (cPtr == 0) ? null : new sdEvent(cPtr, false);
  }

  public sdEvent addEvent(SWIGTYPE_p_std__string time, SWIGTYPE_p_std__string descriptor, SWIGTYPE_p_std__string value) {
    long cPtr = spatdiflib_wrapperJNI.sdEntity_addEvent__SWIG_1(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(time), SWIGTYPE_p_std__string.getCPtr(descriptor), SWIGTYPE_p_std__string.getCPtr(value));
    return (cPtr == 0) ? null : new sdEvent(cPtr, false);
  }

  public void removeEvent(sdEvent event) {
    spatdiflib_wrapperJNI.sdEntity_removeEvent__SWIG_0(swigCPtr, this, sdEvent.getCPtr(event), event);
  }

  public void removeEvent(double time, EDescriptor descriptor) {
    spatdiflib_wrapperJNI.sdEntity_removeEvent__SWIG_1(swigCPtr, this, time, descriptor.swigValue());
  }

  public void removeEvent(SWIGTYPE_p_std__string time, SWIGTYPE_p_std__string descriptor) {
    spatdiflib_wrapperJNI.sdEntity_removeEvent__SWIG_2(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(time), SWIGTYPE_p_std__string.getCPtr(descriptor));
  }

  public void removeAllEvents() {
    spatdiflib_wrapperJNI.sdEntity_removeAllEvents(swigCPtr, this);
  }

  public SWIGTYPE_p_void getValue(double time, EDescriptor descriptor) {
    long cPtr = spatdiflib_wrapperJNI.sdEntity_getValue(swigCPtr, this, time, descriptor.swigValue());
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public SWIGTYPE_p_std__string getValueAsString(double time, EDescriptor descriptor) {
    return new SWIGTYPE_p_std__string(spatdiflib_wrapperJNI.sdEntity_getValueAsString(swigCPtr, this, time, descriptor.swigValue()), true);
  }

  public SWIGTYPE_p_void getNextValue(double time, EDescriptor descriptor) {
    long cPtr = spatdiflib_wrapperJNI.sdEntity_getNextValue(swigCPtr, this, time, descriptor.swigValue());
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public SWIGTYPE_p_void getPreviousValue(double time, EDescriptor descriptor) {
    long cPtr = spatdiflib_wrapperJNI.sdEntity_getPreviousValue(swigCPtr, this, time, descriptor.swigValue());
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

}
