/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package libspatdif;

public class sdEntityCore extends sdEntity {
  private transient long swigCPtr;

  protected sdEntityCore(long cPtr, boolean cMemoryOwn) {
    super(spatdiflib_wrapperJNI.sdEntityCore_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(sdEntityCore obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        spatdiflib_wrapperJNI.delete_sdEntityCore(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public static boolean isCoreDescriptor(EDescriptor descriptor) {
    return spatdiflib_wrapperJNI.sdEntityCore_isCoreDescriptor__SWIG_0(descriptor.swigValue());
  }

  public static boolean isCoreDescriptor(SWIGTYPE_p_std__string descriptor) {
    return spatdiflib_wrapperJNI.sdEntityCore_isCoreDescriptor__SWIG_1(SWIGTYPE_p_std__string.getCPtr(descriptor));
  }

  public SWIGTYPE_p_std__string getName() {
    return new SWIGTYPE_p_std__string(spatdiflib_wrapperJNI.sdEntityCore_getName(swigCPtr, this), true);
  }

  public EKind getKind() {
    return EKind.swigToEnum(spatdiflib_wrapperJNI.sdEntityCore_getKind(swigCPtr, this));
  }

  public SWIGTYPE_p_std__string getKindAsString() {
    return new SWIGTYPE_p_std__string(spatdiflib_wrapperJNI.sdEntityCore_getKindAsString(swigCPtr, this), true);
  }

  public EType getType() {
    return EType.swigToEnum(spatdiflib_wrapperJNI.sdEntityCore_getType(swigCPtr, this));
  }

  public SWIGTYPE_p_std__string getTypeAsString() {
    return new SWIGTYPE_p_std__string(spatdiflib_wrapperJNI.sdEntityCore_getTypeAsString(swigCPtr, this), true);
  }

  public sdEvent addEvent(double time, EDescriptor descriptor, SWIGTYPE_p_void value) {
    long cPtr = spatdiflib_wrapperJNI.sdEntityCore_addEvent__SWIG_0(swigCPtr, this, time, descriptor.swigValue(), SWIGTYPE_p_void.getCPtr(value));
    return (cPtr == 0) ? null : new sdEvent(cPtr, false);
  }

  public sdEvent addEvent(SWIGTYPE_p_std__string time, SWIGTYPE_p_std__string descriptor, SWIGTYPE_p_std__string value) {
    long cPtr = spatdiflib_wrapperJNI.sdEntityCore_addEvent__SWIG_1(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(time), SWIGTYPE_p_std__string.getCPtr(descriptor), SWIGTYPE_p_std__string.getCPtr(value));
    return (cPtr == 0) ? null : new sdEvent(cPtr, false);
  }

  public void removeEvent(double time, EDescriptor descriptor) {
    spatdiflib_wrapperJNI.sdEntityCore_removeEvent__SWIG_0(swigCPtr, this, time, descriptor.swigValue());
  }

  public void removeEvent(SWIGTYPE_p_std__string time, SWIGTYPE_p_std__string descriptor) {
    spatdiflib_wrapperJNI.sdEntityCore_removeEvent__SWIG_1(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(time), SWIGTYPE_p_std__string.getCPtr(descriptor));
  }

  public int getNumberOfEvents() {
    return spatdiflib_wrapperJNI.sdEntityCore_getNumberOfEvents(swigCPtr, this);
  }

  public sdEvent getEvent(double time, EDescriptor descriptor) {
    long cPtr = spatdiflib_wrapperJNI.sdEntityCore_getEvent(swigCPtr, this, time, descriptor.swigValue());
    return (cPtr == 0) ? null : new sdEvent(cPtr, false);
  }

  public SWIGTYPE_p_std__multisetT_sdEvent_p_sdEventCompare_t getEventSet() {
    return new SWIGTYPE_p_std__multisetT_sdEvent_p_sdEventCompare_t(spatdiflib_wrapperJNI.sdEntityCore_getEventSet__SWIG_0(swigCPtr, this), true);
  }

  public SWIGTYPE_p_std__multisetT_sdEvent_p_sdEventCompare_t getEventSet(double time) {
    return new SWIGTYPE_p_std__multisetT_sdEvent_p_sdEventCompare_t(spatdiflib_wrapperJNI.sdEntityCore_getEventSet__SWIG_1(swigCPtr, this, time), true);
  }

  public SWIGTYPE_p_std__multisetT_sdEvent_p_sdEventCompare_t getEventSet(double start, double end) {
    return new SWIGTYPE_p_std__multisetT_sdEvent_p_sdEventCompare_t(spatdiflib_wrapperJNI.sdEntityCore_getEventSet__SWIG_2(swigCPtr, this, start, end), true);
  }

  public SWIGTYPE_p_std__multisetT_sdEvent_p_sdEventCompare_t getEventSet(double start, double end, EDescriptor descriptor) {
    return new SWIGTYPE_p_std__multisetT_sdEvent_p_sdEventCompare_t(spatdiflib_wrapperJNI.sdEntityCore_getEventSet__SWIG_3(swigCPtr, this, start, end, descriptor.swigValue()), true);
  }

  public sdEvent getNextEvent(double time, EDescriptor descriptor) {
    long cPtr = spatdiflib_wrapperJNI.sdEntityCore_getNextEvent(swigCPtr, this, time, descriptor.swigValue());
    return (cPtr == 0) ? null : new sdEvent(cPtr, false);
  }

  public SWIGTYPE_p_std__multisetT_sdEvent_p_sdEventCompare_t getNextEventSet(double time) {
    return new SWIGTYPE_p_std__multisetT_sdEvent_p_sdEventCompare_t(spatdiflib_wrapperJNI.sdEntityCore_getNextEventSet(swigCPtr, this, time), true);
  }

  public double getNextEventTime(double time) {
    return spatdiflib_wrapperJNI.sdEntityCore_getNextEventTime(swigCPtr, this, time);
  }

  public sdEvent getPreviousEvent(double time, EDescriptor descriptor) {
    long cPtr = spatdiflib_wrapperJNI.sdEntityCore_getPreviousEvent(swigCPtr, this, time, descriptor.swigValue());
    return (cPtr == 0) ? null : new sdEvent(cPtr, false);
  }

  public SWIGTYPE_p_std__multisetT_sdEvent_p_sdEventCompare_t getPreviousEventSet(double time) {
    return new SWIGTYPE_p_std__multisetT_sdEvent_p_sdEventCompare_t(spatdiflib_wrapperJNI.sdEntityCore_getPreviousEventSet(swigCPtr, this, time), true);
  }

  public double getPreviousEventTime(double time) {
    return spatdiflib_wrapperJNI.sdEntityCore_getPreviousEventTime(swigCPtr, this, time);
  }

  public sdEvent getFirstEvent(EDescriptor descriptor) {
    long cPtr = spatdiflib_wrapperJNI.sdEntityCore_getFirstEvent(swigCPtr, this, descriptor.swigValue());
    return (cPtr == 0) ? null : new sdEvent(cPtr, false);
  }

  public SWIGTYPE_p_std__multisetT_sdEvent_p_sdEventCompare_t getFirstEventSet() {
    return new SWIGTYPE_p_std__multisetT_sdEvent_p_sdEventCompare_t(spatdiflib_wrapperJNI.sdEntityCore_getFirstEventSet(swigCPtr, this), true);
  }

  public double getFirstEventTime() {
    return spatdiflib_wrapperJNI.sdEntityCore_getFirstEventTime(swigCPtr, this);
  }

  public sdEvent getLastEvent(EDescriptor descriptor) {
    long cPtr = spatdiflib_wrapperJNI.sdEntityCore_getLastEvent(swigCPtr, this, descriptor.swigValue());
    return (cPtr == 0) ? null : new sdEvent(cPtr, false);
  }

  public SWIGTYPE_p_std__multisetT_sdEvent_p_sdEventCompare_t getLastEventSet() {
    return new SWIGTYPE_p_std__multisetT_sdEvent_p_sdEventCompare_t(spatdiflib_wrapperJNI.sdEntityCore_getLastEventSet(swigCPtr, this), true);
  }

  public double getLastEventTime() {
    return spatdiflib_wrapperJNI.sdEntityCore_getLastEventTime(swigCPtr, this);
  }

  public SWIGTYPE_p_void getValue(double time, EDescriptor descriptor) {
    long cPtr = spatdiflib_wrapperJNI.sdEntityCore_getValue(swigCPtr, this, time, descriptor.swigValue());
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public SWIGTYPE_p_std__string getValueAsString(double time, EDescriptor descriptor) {
    return new SWIGTYPE_p_std__string(spatdiflib_wrapperJNI.sdEntityCore_getValueAsString(swigCPtr, this, time, descriptor.swigValue()), true);
  }

  public boolean activateInterpolation(EDescriptor descriptor) {
    return spatdiflib_wrapperJNI.sdEntityCore_activateInterpolation__SWIG_0(swigCPtr, this, descriptor.swigValue());
  }

  public boolean activateInterpolation() {
    return spatdiflib_wrapperJNI.sdEntityCore_activateInterpolation__SWIG_1(swigCPtr, this);
  }

  public boolean deactivateInterpolation(EDescriptor descriptor) {
    return spatdiflib_wrapperJNI.sdEntityCore_deactivateInterpolation__SWIG_0(swigCPtr, this, descriptor.swigValue());
  }

  public boolean deactivateInterpolation() {
    return spatdiflib_wrapperJNI.sdEntityCore_deactivateInterpolation__SWIG_1(swigCPtr, this);
  }

  public boolean isInterpolationActivated(EDescriptor descriptor) {
    return spatdiflib_wrapperJNI.sdEntityCore_isInterpolationActivated(swigCPtr, this, descriptor.swigValue());
  }

  public static boolean sortAlphabetically(sdEntityCore leftEntity, sdEntityCore rightEntity) {
    return spatdiflib_wrapperJNI.sdEntityCore_sortAlphabetically(sdEntityCore.getCPtr(leftEntity), leftEntity, sdEntityCore.getCPtr(rightEntity), rightEntity);
  }

}
