/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package libspatdif;

public class sdEntityExtensionMedia extends sdEntityExtension {
  private transient long swigCPtr;

  protected sdEntityExtensionMedia(long cPtr, boolean cMemoryOwn) {
    super(spatdiflib_wrapperJNI.sdEntityExtensionMedia_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(sdEntityExtensionMedia obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        spatdiflib_wrapperJNI.delete_sdEntityExtensionMedia(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public static EExtension getExtensionName() {
    return EExtension.swigToEnum(spatdiflib_wrapperJNI.sdEntityExtensionMedia_extensionName_get());
  }

  public static SWIGTYPE_p_std__string getExtensionNameAsString() {
    return new SWIGTYPE_p_std__string(spatdiflib_wrapperJNI.sdEntityExtensionMedia_extensionNameAsString_get(), true);
  }

  public sdEvent addEvent(double time, EDescriptor descriptor, SWIGTYPE_p_void value) {
    long cPtr = spatdiflib_wrapperJNI.sdEntityExtensionMedia_addEvent__SWIG_0(swigCPtr, this, time, descriptor.swigValue(), SWIGTYPE_p_void.getCPtr(value));
    return (cPtr == 0) ? null : new sdEvent(cPtr, false);
  }

  public sdEvent addEvent(SWIGTYPE_p_std__string time, SWIGTYPE_p_std__string descriptor, SWIGTYPE_p_std__string value) {
    long cPtr = spatdiflib_wrapperJNI.sdEntityExtensionMedia_addEvent__SWIG_1(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(time), SWIGTYPE_p_std__string.getCPtr(descriptor), SWIGTYPE_p_std__string.getCPtr(value));
    return (cPtr == 0) ? null : new sdEvent(cPtr, false);
  }

  public void removeEvent(SWIGTYPE_p_std__string time, SWIGTYPE_p_std__string descriptor) {
    spatdiflib_wrapperJNI.sdEntityExtensionMedia_removeEvent(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(time), SWIGTYPE_p_std__string.getCPtr(descriptor));
  }

  public SWIGTYPE_p_std__string getValueAsString(double time, EDescriptor descriptor) {
    return new SWIGTYPE_p_std__string(spatdiflib_wrapperJNI.sdEntityExtensionMedia_getValueAsString(swigCPtr, this, time, descriptor.swigValue()), true);
  }

  public boolean activateInterpolation(EDescriptor descriptor) {
    return spatdiflib_wrapperJNI.sdEntityExtensionMedia_activateInterpolation__SWIG_0(swigCPtr, this, descriptor.swigValue());
  }

  public boolean activateInterpolation() {
    return spatdiflib_wrapperJNI.sdEntityExtensionMedia_activateInterpolation__SWIG_1(swigCPtr, this);
  }

  public boolean deactivateInterpolation(EDescriptor descriptor) {
    return spatdiflib_wrapperJNI.sdEntityExtensionMedia_deactivateInterpolation__SWIG_0(swigCPtr, this, descriptor.swigValue());
  }

  public boolean deactivateInterpolation() {
    return spatdiflib_wrapperJNI.sdEntityExtensionMedia_deactivateInterpolation__SWIG_1(swigCPtr, this);
  }

  public boolean isInterpolationActivated(EDescriptor descriptor) {
    return spatdiflib_wrapperJNI.sdEntityExtensionMedia_isInterpolationActivated(swigCPtr, this, descriptor.swigValue());
  }

  public EExtension getExtensionName() {
    return EExtension.swigToEnum(spatdiflib_wrapperJNI.sdEntityExtensionMedia_getExtensionName(swigCPtr, this));
  }

  public SWIGTYPE_p_std__string getExtensionNameAsString() {
    return new SWIGTYPE_p_std__string(spatdiflib_wrapperJNI.sdEntityExtensionMedia_getExtensionNameAsString(swigCPtr, this), true);
  }

}
