/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package libspatdif;

public class sdEventCore extends sdEvent {
  private transient long swigCPtr;

  protected sdEventCore(long cPtr, boolean cMemoryOwn) {
    super(spatdiflib_wrapperJNI.sdEventCore_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(sdEventCore obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        spatdiflib_wrapperJNI.delete_sdEventCore(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public static long getNumberOfDescriptors() {
    return spatdiflib_wrapperJNI.sdEventCore_numberOfDescriptors_get();
  }

  public static sdDescriptor getDescriptors() {
    long cPtr = spatdiflib_wrapperJNI.sdEventCore_descriptors_get();
    return (cPtr == 0) ? null : new sdDescriptor(cPtr, false);
  }

  public SWIGTYPE_p_std__string getValueAsString() {
    return new SWIGTYPE_p_std__string(spatdiflib_wrapperJNI.sdEventCore_getValueAsString(swigCPtr, this), true);
  }

  public SWIGTYPE_p_std__string getDescriptorAsString() {
    return new SWIGTYPE_p_std__string(spatdiflib_wrapperJNI.sdEventCore_getDescriptorAsString(swigCPtr, this), true);
  }

}
