/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package libspatdif;

public class sdEvent {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected sdEvent(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(sdEvent obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        spatdiflib_wrapperJNI.delete_sdEvent(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void set(double time, EDescriptor descriptor, SWIGTYPE_p_void value) {
    spatdiflib_wrapperJNI.sdEvent_set(swigCPtr, this, time, descriptor.swigValue(), SWIGTYPE_p_void.getCPtr(value));
  }

  public void setTime(double time) {
    spatdiflib_wrapperJNI.sdEvent_setTime__SWIG_0(swigCPtr, this, time);
  }

  public void setTime(SWIGTYPE_p_std__string timeString) {
    spatdiflib_wrapperJNI.sdEvent_setTime__SWIG_1(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(timeString));
  }

  public double getTime() {
    return spatdiflib_wrapperJNI.sdEvent_getTime(swigCPtr, this);
  }

  public SWIGTYPE_p_std__string getTimeAsString() {
    return new SWIGTYPE_p_std__string(spatdiflib_wrapperJNI.sdEvent_getTimeAsString(swigCPtr, this), true);
  }

  public boolean setValue(EDescriptor descriptor, SWIGTYPE_p_void value) {
    return spatdiflib_wrapperJNI.sdEvent_setValue__SWIG_0(swigCPtr, this, descriptor.swigValue(), SWIGTYPE_p_void.getCPtr(value));
  }

  public boolean setValue(SWIGTYPE_p_std__string descriptor, SWIGTYPE_p_std__string value) {
    return spatdiflib_wrapperJNI.sdEvent_setValue__SWIG_1(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(descriptor), SWIGTYPE_p_std__string.getCPtr(value));
  }

  public EDescriptor getDescriptor() {
    return EDescriptor.swigToEnum(spatdiflib_wrapperJNI.sdEvent_getDescriptor(swigCPtr, this));
  }

  public SWIGTYPE_p_std__string getDescriptorAsString() {
    return new SWIGTYPE_p_std__string(spatdiflib_wrapperJNI.sdEvent_getDescriptorAsString(swigCPtr, this), true);
  }

  public SWIGTYPE_p_void getValue() {
    long cPtr = spatdiflib_wrapperJNI.sdEvent_getValue(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public SWIGTYPE_p_std__string getValueAsString() {
    return new SWIGTYPE_p_std__string(spatdiflib_wrapperJNI.sdEvent_getValueAsString(swigCPtr, this), true);
  }

}
