/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package libspatdif;

public class sdExtensible {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected sdExtensible(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(sdExtensible obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        spatdiflib_wrapperJNI.delete_sdExtensible(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public sdEntityExtension getResponsibleExtension(EDescriptor descriptor) {
    long cPtr = spatdiflib_wrapperJNI.sdExtensible_getResponsibleExtension(swigCPtr, this, descriptor.swigValue());
    return (cPtr == 0) ? null : new sdEntityExtension(cPtr, false);
  }

  public sdExtensible() {
    this(spatdiflib_wrapperJNI.new_sdExtensible(), true);
  }

}
