/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package libspatdif;

public class sdGlobalEvent {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected sdGlobalEvent(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(sdGlobalEvent obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        spatdiflib_wrapperJNI.delete_sdGlobalEvent(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public sdGlobalEvent(sdEvent event, SWIGTYPE_p_std__string entityName, EKind kind) {
    this(spatdiflib_wrapperJNI.new_sdGlobalEvent(sdEvent.getCPtr(event), event, SWIGTYPE_p_std__string.getCPtr(entityName), kind.swigValue()), true);
  }

  public sdEvent getEvent() {
    long cPtr = spatdiflib_wrapperJNI.sdGlobalEvent_getEvent(swigCPtr, this);
    return (cPtr == 0) ? null : new sdEvent(cPtr, false);
  }

  public SWIGTYPE_p_std__string getEntityName() {
    return new SWIGTYPE_p_std__string(spatdiflib_wrapperJNI.sdGlobalEvent_getEntityName(swigCPtr, this), true);
  }

  public EKind getKind() {
    return EKind.swigToEnum(spatdiflib_wrapperJNI.sdGlobalEvent_getKind(swigCPtr, this));
  }

  public SWIGTYPE_p_std__string getKindAsString() {
    return new SWIGTYPE_p_std__string(spatdiflib_wrapperJNI.sdGlobalEvent_getKindAsString(swigCPtr, this), true);
  }

}
