/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package libspatdif;

public class sdInterpolation {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected sdInterpolation(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(sdInterpolation obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        spatdiflib_wrapperJNI.delete_sdInterpolation(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public boolean activateInterpolation(EDescriptor descriptor) {
    return spatdiflib_wrapperJNI.sdInterpolation_activateInterpolation__SWIG_1(swigCPtr, this, descriptor.swigValue());
  }

  public boolean activateInterpolation() {
    return spatdiflib_wrapperJNI.sdInterpolation_activateInterpolation__SWIG_2(swigCPtr, this);
  }

  public boolean deactivateInterpolation(EDescriptor descriptor) {
    return spatdiflib_wrapperJNI.sdInterpolation_deactivateInterpolation__SWIG_1(swigCPtr, this, descriptor.swigValue());
  }

  public boolean deactivateInterpolation() {
    return spatdiflib_wrapperJNI.sdInterpolation_deactivateInterpolation__SWIG_2(swigCPtr, this);
  }

  public boolean isInterpolationActivated(EDescriptor descriptor) {
    return spatdiflib_wrapperJNI.sdInterpolation_isInterpolationActivated(swigCPtr, this, descriptor.swigValue());
  }

}
