/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package libspatdif;

public class sdInfo {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected sdInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(sdInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        spatdiflib_wrapperJNI.delete_sdInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public sdInfo() {
    this(spatdiflib_wrapperJNI.new_sdInfo__SWIG_0(), true);
  }

  public sdInfo(SWIGTYPE_p_std__string author, SWIGTYPE_p_std__string host, sdDate date, SWIGTYPE_p_std__string session, SWIGTYPE_p_std__string location, SWIGTYPE_p_std__string annotation) {
    this(spatdiflib_wrapperJNI.new_sdInfo__SWIG_1(SWIGTYPE_p_std__string.getCPtr(author), SWIGTYPE_p_std__string.getCPtr(host), sdDate.getCPtr(date), date, SWIGTYPE_p_std__string.getCPtr(session), SWIGTYPE_p_std__string.getCPtr(location), SWIGTYPE_p_std__string.getCPtr(annotation)), true);
  }

  public sdInfo(SWIGTYPE_p_std__string author, SWIGTYPE_p_std__string host, SWIGTYPE_p_std__string date, SWIGTYPE_p_std__string session, SWIGTYPE_p_std__string location, SWIGTYPE_p_std__string annotation) {
    this(spatdiflib_wrapperJNI.new_sdInfo__SWIG_2(SWIGTYPE_p_std__string.getCPtr(author), SWIGTYPE_p_std__string.getCPtr(host), SWIGTYPE_p_std__string.getCPtr(date), SWIGTYPE_p_std__string.getCPtr(session), SWIGTYPE_p_std__string.getCPtr(location), SWIGTYPE_p_std__string.getCPtr(annotation)), true);
  }

  public sdInfo(String author, String host, String date, String session, String location, String annotation) {
    this(spatdiflib_wrapperJNI.new_sdInfo__SWIG_3(author, host, date, session, location, annotation), true);
  }

  public void setAuthor(SWIGTYPE_p_std__string author) {
    spatdiflib_wrapperJNI.sdInfo_setAuthor(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(author));
  }

  public void setHost(SWIGTYPE_p_std__string host) {
    spatdiflib_wrapperJNI.sdInfo_setHost(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(host));
  }

  public void setDate(sdDate date) {
    spatdiflib_wrapperJNI.sdInfo_setDate__SWIG_0(swigCPtr, this, sdDate.getCPtr(date), date);
  }

  public void setDate(SWIGTYPE_p_std__string date) {
    spatdiflib_wrapperJNI.sdInfo_setDate__SWIG_1(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(date));
  }

  public void setSession(SWIGTYPE_p_std__string session) {
    spatdiflib_wrapperJNI.sdInfo_setSession(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(session));
  }

  public void setLocation(SWIGTYPE_p_std__string location) {
    spatdiflib_wrapperJNI.sdInfo_setLocation(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(location));
  }

  public void setAnnotation(SWIGTYPE_p_std__string annotation) {
    spatdiflib_wrapperJNI.sdInfo_setAnnotation(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(annotation));
  }

  public void set(SWIGTYPE_p_std__string author, SWIGTYPE_p_std__string host, sdDate date, SWIGTYPE_p_std__string session, SWIGTYPE_p_std__string location, SWIGTYPE_p_std__string annotation) {
    spatdiflib_wrapperJNI.sdInfo_set(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(author), SWIGTYPE_p_std__string.getCPtr(host), sdDate.getCPtr(date), date, SWIGTYPE_p_std__string.getCPtr(session), SWIGTYPE_p_std__string.getCPtr(location), SWIGTYPE_p_std__string.getCPtr(annotation));
  }

  public SWIGTYPE_p_std__string getAuthor() {
    return new SWIGTYPE_p_std__string(spatdiflib_wrapperJNI.sdInfo_getAuthor(swigCPtr, this), true);
  }

  public SWIGTYPE_p_std__string getHost() {
    return new SWIGTYPE_p_std__string(spatdiflib_wrapperJNI.sdInfo_getHost(swigCPtr, this), true);
  }

  public sdDate getDate() {
    return new sdDate(spatdiflib_wrapperJNI.sdInfo_getDate(swigCPtr, this), true);
  }

  public SWIGTYPE_p_std__string getDateAsString() {
    return new SWIGTYPE_p_std__string(spatdiflib_wrapperJNI.sdInfo_getDateAsString(swigCPtr, this), true);
  }

  public SWIGTYPE_p_std__string getSession() {
    return new SWIGTYPE_p_std__string(spatdiflib_wrapperJNI.sdInfo_getSession(swigCPtr, this), true);
  }

  public SWIGTYPE_p_std__string getLocation() {
    return new SWIGTYPE_p_std__string(spatdiflib_wrapperJNI.sdInfo_getLocation(swigCPtr, this), true);
  }

  public SWIGTYPE_p_std__string getAnnotation() {
    return new SWIGTYPE_p_std__string(spatdiflib_wrapperJNI.sdInfo_getAnnotation(swigCPtr, this), true);
  }

}
