/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package libspatdif;

public class sdLoader {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected sdLoader(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(sdLoader obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        spatdiflib_wrapperJNI.delete_sdLoader(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static sdScene sceneFromXML(SWIGTYPE_p_std__string xmlString) {
    return new sdScene(spatdiflib_wrapperJNI.sdLoader_sceneFromXML(SWIGTYPE_p_std__string.getCPtr(xmlString)), true);
  }

  public static sdScene sceneFromJSON(SWIGTYPE_p_std__string jsonString) {
    return new sdScene(spatdiflib_wrapperJNI.sdLoader_sceneFromJSON(SWIGTYPE_p_std__string.getCPtr(jsonString)), true);
  }

  public static sdScene sceneFromYAML(SWIGTYPE_p_std__string yamlString) {
    return new sdScene(spatdiflib_wrapperJNI.sdLoader_sceneFromYAML(SWIGTYPE_p_std__string.getCPtr(yamlString)), true);
  }

  public sdLoader() {
    this(spatdiflib_wrapperJNI.new_sdLoader(), true);
  }

}
