/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package libspatdif;

public class sdReport {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected sdReport(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(sdReport obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        spatdiflib_wrapperJNI.delete_sdReport(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setEntity(sdEntityCore value) {
    spatdiflib_wrapperJNI.sdReport_entity_set(swigCPtr, this, sdEntityCore.getCPtr(value), value);
  }

  public sdEntityCore getEntity() {
    long cPtr = spatdiflib_wrapperJNI.sdReport_entity_get(swigCPtr, this);
    return (cPtr == 0) ? null : new sdEntityCore(cPtr, false);
  }

  public void setEventSet(SWIGTYPE_p_std__multisetT_sdEvent_p_sdEventCompare_t value) {
    spatdiflib_wrapperJNI.sdReport_eventSet_set(swigCPtr, this, SWIGTYPE_p_std__multisetT_sdEvent_p_sdEventCompare_t.getCPtr(value));
  }

  public SWIGTYPE_p_std__multisetT_sdEvent_p_sdEventCompare_t getEventSet() {
    long cPtr = spatdiflib_wrapperJNI.sdReport_eventSet_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_std__multisetT_sdEvent_p_sdEventCompare_t(cPtr, false);
  }

  public sdReport() {
    this(spatdiflib_wrapperJNI.new_sdReport(), true);
  }

}
