/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package libspatdif;

public class sdSaver {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected sdSaver(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(sdSaver obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        spatdiflib_wrapperJNI.delete_sdSaver(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static SWIGTYPE_p_std__string XMLFromScene(sdScene scene) {
    return new SWIGTYPE_p_std__string(spatdiflib_wrapperJNI.sdSaver_XMLFromScene(sdScene.getCPtr(scene), scene), true);
  }

  public static SWIGTYPE_p_std__string JSONFromScene(sdScene scene) {
    return new SWIGTYPE_p_std__string(spatdiflib_wrapperJNI.sdSaver_JSONFromScene(sdScene.getCPtr(scene), scene), true);
  }

  public static SWIGTYPE_p_std__string YAMLFromScene(sdScene scene) {
    return new SWIGTYPE_p_std__string(spatdiflib_wrapperJNI.sdSaver_YAMLFromScene(sdScene.getCPtr(scene), scene), true);
  }

  public sdSaver() {
    this(spatdiflib_wrapperJNI.new_sdSaver(), true);
  }

}
