/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package libspatdif;

public class sdScene extends sdTrajectoryHandler {
  private transient long swigCPtr;

  protected sdScene(long cPtr, boolean cMemoryOwn) {
    super(spatdiflib_wrapperJNI.sdScene_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(sdScene obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        spatdiflib_wrapperJNI.delete_sdScene(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public sdScene() {
    this(spatdiflib_wrapperJNI.new_sdScene__SWIG_0(), true);
  }

  public sdScene(sdInfo info) {
    this(spatdiflib_wrapperJNI.new_sdScene__SWIG_1(sdInfo.getCPtr(info), info), true);
  }

  public sdScene(sdInfo info, EOrdering ordering) {
    this(spatdiflib_wrapperJNI.new_sdScene__SWIG_2(sdInfo.getCPtr(info), info, ordering.swigValue()), true);
  }

  public void setInfo(sdInfo info) {
    spatdiflib_wrapperJNI.sdScene_setInfo(swigCPtr, this, sdInfo.getCPtr(info), info);
  }

  public sdInfo getInfo() {
    return new sdInfo(spatdiflib_wrapperJNI.sdScene_getInfo(swigCPtr, this), true);
  }

  public EOrdering getOrdering() {
    return EOrdering.swigToEnum(spatdiflib_wrapperJNI.sdScene_getOrdering(swigCPtr, this));
  }

  public SWIGTYPE_p_std__string getOrderingAsString() {
    return new SWIGTYPE_p_std__string(spatdiflib_wrapperJNI.sdScene_getOrderingAsString(swigCPtr, this), true);
  }

  public void setOrdering(EOrdering ordering) {
    spatdiflib_wrapperJNI.sdScene_setOrdering__SWIG_0(swigCPtr, this, ordering.swigValue());
  }

  public void setOrdering(SWIGTYPE_p_std__string string) {
    spatdiflib_wrapperJNI.sdScene_setOrdering__SWIG_1(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(string));
  }

  public SWIGTYPE_p_std__string getEntityName(int index) {
    return new SWIGTYPE_p_std__string(spatdiflib_wrapperJNI.sdScene_getEntityName(swigCPtr, this, index), true);
  }

  public SWIGTYPE_p_std__vectorT_std__string_t getEntityNames() {
    return new SWIGTYPE_p_std__vectorT_std__string_t(spatdiflib_wrapperJNI.sdScene_getEntityNames(swigCPtr, this), true);
  }

  public sdEntityCore getEntity(SWIGTYPE_p_std__string name) {
    long cPtr = spatdiflib_wrapperJNI.sdScene_getEntity(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(name));
    return (cPtr == 0) ? null : new sdEntityCore(cPtr, false);
  }

  public SWIGTYPE_p_std__vectorT_sdEntityCore_p_t getEntityVector() {
    return new SWIGTYPE_p_std__vectorT_sdEntityCore_p_t(spatdiflib_wrapperJNI.sdScene_getEntityVector(swigCPtr, this), true);
  }

  public long getNumberOfEntities() {
    return spatdiflib_wrapperJNI.sdScene_getNumberOfEntities(swigCPtr, this);
  }

  public sdEntityCore addEntity(SWIGTYPE_p_std__string name, EKind kind) {
    long cPtr = spatdiflib_wrapperJNI.sdScene_addEntity__SWIG_0(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(name), kind.swigValue());
    return (cPtr == 0) ? null : new sdEntityCore(cPtr, false);
  }

  public sdEntityCore addEntity(SWIGTYPE_p_std__string name) {
    long cPtr = spatdiflib_wrapperJNI.sdScene_addEntity__SWIG_1(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(name));
    return (cPtr == 0) ? null : new sdEntityCore(cPtr, false);
  }

  public void removeEntity(SWIGTYPE_p_std__string name) {
    spatdiflib_wrapperJNI.sdScene_removeEntity__SWIG_0(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(name));
  }

  public void removeEntity(sdEntityCore entityCore) {
    spatdiflib_wrapperJNI.sdScene_removeEntity__SWIG_1(swigCPtr, this, sdEntityCore.getCPtr(entityCore), entityCore);
  }

  public void removeAllEntities() {
    spatdiflib_wrapperJNI.sdScene_removeAllEntities(swigCPtr, this);
  }

  public void setValue(SWIGTYPE_p_std__string name, double time, EDescriptor descriptor, SWIGTYPE_p_void value) {
    spatdiflib_wrapperJNI.sdScene_setValue(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(name), time, descriptor.swigValue(), SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getValue(SWIGTYPE_p_std__string name, double time, EDescriptor descriptor) {
    long cPtr = spatdiflib_wrapperJNI.sdScene_getValue(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(name), time, descriptor.swigValue());
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public EExtension getActivatedExtension(int index) {
    return EExtension.swigToEnum(spatdiflib_wrapperJNI.sdScene_getActivatedExtension(swigCPtr, this, index));
  }

  public int getNumberOfActivatedExtensions() {
    return spatdiflib_wrapperJNI.sdScene_getNumberOfActivatedExtensions(swigCPtr, this);
  }

  public SWIGTYPE_p_std__vectorT_EExtension_t getActivatedExtensions() {
    return new SWIGTYPE_p_std__vectorT_EExtension_t(spatdiflib_wrapperJNI.sdScene_getActivatedExtensions(swigCPtr, this), true);
  }

  public SWIGTYPE_p_std__vectorT_std__string_t getActivatedExtensionsAsStrings() {
    return new SWIGTYPE_p_std__vectorT_std__string_t(spatdiflib_wrapperJNI.sdScene_getActivatedExtensionsAsStrings(swigCPtr, this), true);
  }

  public void addExtension(EExtension extension) {
    spatdiflib_wrapperJNI.sdScene_addExtension__SWIG_0(swigCPtr, this, extension.swigValue());
  }

  public void addExtension(SWIGTYPE_p_std__string extension) {
    spatdiflib_wrapperJNI.sdScene_addExtension__SWIG_1(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(extension));
  }

  public boolean isExtensionActivated(EExtension extension) {
    return spatdiflib_wrapperJNI.sdScene_isExtensionActivated__SWIG_0(swigCPtr, this, extension.swigValue());
  }

  public boolean isExtensionActivated(SWIGTYPE_p_std__string extensionString) {
    return spatdiflib_wrapperJNI.sdScene_isExtensionActivated__SWIG_1(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(extensionString));
  }

  public void removeExtension(EExtension extension) {
    spatdiflib_wrapperJNI.sdScene_removeExtension__SWIG_0(swigCPtr, this, extension.swigValue());
  }

  public void removeExtension(SWIGTYPE_p_std__string extension) {
    spatdiflib_wrapperJNI.sdScene_removeExtension__SWIG_1(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(extension));
  }

  public void removeAllExtensions() {
    spatdiflib_wrapperJNI.sdScene_removeAllExtensions(swigCPtr, this);
  }

  public SWIGTYPE_p_std__vectorT_sdReport_t getNextEventSetsFromAllEntities(double time) {
    return new SWIGTYPE_p_std__vectorT_sdReport_t(spatdiflib_wrapperJNI.sdScene_getNextEventSetsFromAllEntities(swigCPtr, this, time), true);
  }

  public SWIGTYPE_p_std__vectorT_sdReport_t getPreviousEventSetsFromAllEntities(double time) {
    return new SWIGTYPE_p_std__vectorT_sdReport_t(spatdiflib_wrapperJNI.sdScene_getPreviousEventSetsFromAllEntities(swigCPtr, this, time), true);
  }

  public SWIGTYPE_p_std__vectorT_sdReport_t getFirstEventSetsFromAllEntities() {
    return new SWIGTYPE_p_std__vectorT_sdReport_t(spatdiflib_wrapperJNI.sdScene_getFirstEventSetsFromAllEntities(swigCPtr, this), true);
  }

  public SWIGTYPE_p_std__vectorT_sdReport_t getLastEventSetsFromAllEntities() {
    return new SWIGTYPE_p_std__vectorT_sdReport_t(spatdiflib_wrapperJNI.sdScene_getLastEventSetsFromAllEntities(swigCPtr, this), true);
  }

  public SWIGTYPE_p_std__vectorT_sdReport_t getEventSetsFromAllEntities(double time) {
    return new SWIGTYPE_p_std__vectorT_sdReport_t(spatdiflib_wrapperJNI.sdScene_getEventSetsFromAllEntities__SWIG_0(swigCPtr, this, time), true);
  }

  public SWIGTYPE_p_std__vectorT_sdReport_t getEventSetsFromAllEntities(double start, double end) {
    return new SWIGTYPE_p_std__vectorT_sdReport_t(spatdiflib_wrapperJNI.sdScene_getEventSetsFromAllEntities__SWIG_1(swigCPtr, this, start, end), true);
  }

  public SWIGTYPE_p_std__vectorT_sdReport_t getFirstEventSets() {
    return new SWIGTYPE_p_std__vectorT_sdReport_t(spatdiflib_wrapperJNI.sdScene_getFirstEventSets(swigCPtr, this), true);
  }

  public SWIGTYPE_p_std__vectorT_sdReport_t getNextEventSets(double time) {
    return new SWIGTYPE_p_std__vectorT_sdReport_t(spatdiflib_wrapperJNI.sdScene_getNextEventSets(swigCPtr, this, time), true);
  }

  public double getNextEventTime(double time) {
    return spatdiflib_wrapperJNI.sdScene_getNextEventTime(swigCPtr, this, time);
  }

  public double getDeltaTimeToNextEvent(double time) {
    return spatdiflib_wrapperJNI.sdScene_getDeltaTimeToNextEvent(swigCPtr, this, time);
  }

  public SWIGTYPE_p_std__string dump(boolean consoleOut) {
    return new SWIGTYPE_p_std__string(spatdiflib_wrapperJNI.sdScene_dump__SWIG_0(swigCPtr, this, consoleOut), true);
  }

  public SWIGTYPE_p_std__string dump() {
    return new SWIGTYPE_p_std__string(spatdiflib_wrapperJNI.sdScene_dump__SWIG_1(swigCPtr, this), true);
  }

}
